### PR TITLE
Middleware lwip abstraction

### PR DESCRIPTION
**Pull request by matt001k**
This adds:

- API for UDP abstraction necessary in middleware
- Documentation explaining how middleware operates at a high level

### CODE REVIEW

**Comment by towynlin** [comment]
Thanks for pushing this forward — I must not have explained some Bristlemouth fundamentals very well. Sorry about that.

The Bristlemouth specification does not mention UDP. We are not sending datagrams with port numbers. I think UDP should not be mentioned in the naming of functions or modules in a Bristlemouth library.

The lwip usage of UDP is, I believe, just a way to shoehorn Bristlemouth middleware into lwip's API structure. LwIP has APIs for UDP; Bristlemouth does not. If someone's not using lwip, then they should never need to think about UDP.

The naming here at least needs discussion and likely changes — the docs and diagram too. When we talk about Bristlemouth middleware, we mean pub-sub. I don't understand the separation between "middleware" and "pub-sub" in the diagram.

Please schedule a discussion meeting either for tomorrow (I'll be working from home) or Friday when we're all in office.

**Comment by matt001k** [comment]
@towynlin sounds good and thanks for the feedback.
To answer your question about the separation between middleware and pub-sub,
they are two separate modules in code and this was what I was trying to indicate in the diagram (not that they were technically two different things).
I will schedule something Friday to discuss further!

**Comment by matt001k** [comment]
A couple of more things to note here about this. Currently with lwip's implementation of UDP, we are communicating to a specific port on the middleware (4321).
This port is bound to a specific pcb (protocol control block), which will only receive data on that port and filter out other messages.
We could use lwip's raw API, which would greatly reduce the amount of abstraction API in the `bm_ip.h` file.
But, to maintain backwards compatibility, we would have to fill in a fake UDP header (8 bytes) with what we currently have today.

**Comment by towynlin** [comment]
We had a great discussion today that also included @spiderkeys, and we learned about the original intent behind Bristlemouth's usage of UDP.

Bristlemouth middleware as described in the specification is agnostic to the implementation and even allows multiple different middleware implementations to run side-by-side simultaneously. This is accomplished by using UDP, and mapping a UDP port number to a particular implementation. The current implementation of middleware uses port 4321.

The main restriction on a middleware implementation is that it needs to work without unicast routing. Only multicast (global and link-local) destination IPv6 addresses are supported in order to keep the routing layer minimal.

As an extension example, if someone wanted in the future to create a separate zenoh middleware implementation, that could be possible, and it would bind and send to a different UDP port. It would make use of the same tables of neighbors and resource interests that are built by BCMP.

So, follow-ups:

- The code here looks good to me, though maybe the docs and diagram should still change. Thoughts @matt001k?
- Since the intent behind UDP isn't documented anywhere, I'll take an action item to make some edits to public docs, probably the "Middleware Protocol" document here: https://bristlemouth.notion.site/Bristlemouth-Protocol-Documentation-83b18bf2f00a4af99fb534348d0366c4

**Comment by matt001k** [comment]
@towynlin I believe maybe one of the following should be done:

- The document clearly labelling that the diagram has the specific modules/sources involved in the middleware (there is a middleware.c file and a pubsub.c file that do specific things)
- Combine the middleware and pubsub section on the diagram to avoid any confusion (although this does not exactly represent the structure of the code)

Thoughts on either of these?

**Comment by towynlin** [comment]
Actually, looking again at the diagram with fresh eyes after our discussion, I think it makes sense. We can always keep refining it in the future. I don't have any specific changes that seem required.

I look forward to the day when there are lots of folks making Bristlemouth things, and someone points out how they were confused by some particular part of the documentation. 😄

**Review by towynlin — APPROVED** [review]

**Pull request merged**
